services:
  db:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      .env
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    container_name: ktor_api
    environment:
        DATABASE_URL : "jdbc:postgresql://db:5432/postgres"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./project-api:/app
    restart: unless-stopped
