ktor:
  application:
    modules:
      - mx.unam.fciencias.ids.eq1.ApplicationKt.module
  deployment:
    port: 8080
    connectionGroupSize: 2
    workerGroupSize: 5
    callGroupSize: 10
    shutdownGracePeriod: 2000
    shutdownTimeout: 3000
    maxInitialLineLength: 2048
    maxHeaderSize: 1024
    maxChunkSize: 42
jwt:
  secret: "secret"
  issuer: "http://0.0.0.0:8080/"
  audience: "http://0.0.0.0:8080/hello"
  realm: "Access to 'hello'"
