services:
  db:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    env_file:
      .env
    volumes:
      - ./data:/var/lib/postgresql/data  # Persist data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Runs on first start
    ports:
      - "5432:5432"

